### ISSUE TITLE
sd or se?

### ISSUE THREAD

**Issue by enfascination** [williamaeberhard/glmrob.nb#1]
According to the demo, this code returns standard errors, but according to the code (and the column naming) it seems to return standard deviations.  In the meantime, I am assuming that the model returns standard deviations, and I am using boot() and boot.ci() for empirical standard errors and ci's.  But they are slow, so if you are already including a less unwieldy method for computing the kind of standard errors you report in the paper, I would be happy for clarification.

Also, for your information, while getting the code to work, I kept running into this error:
```
Error in while (abs(max(beta1 - beta0)) > tol & it.mu < maxit) { : 
  missing value where TRUE/FALSE needed

```
I ultimately got around it by explicitly setting the intercept of my input formula/model matrix (as computed by model.matrix) to zero (y ~ 0 + x).

**Comment by williamaeberhard** [comment]
The `$stdev` element of the output of `glmrob.nb` is the vector of estimated standard errors of the estimated beta. To be precise, these are the square root of the diagonal elements of the asymptotic variance-covariance matrix computed from the sandwich formula (equation (6) of the Biometrics paper) with the (1/n) coefficient and where the true beta has been replaced by the estimated one.  I guess I could rename it `$se` in the next version to avoid further confusion (although these are technically standard deviations).

The error you're getting is likely due to beta going to `Inf` or `NaN` within the iterations, which can happen on some samples/designs with redescending robust estimators. The best general advice I can give is to try many different starting values through the optional argument `param.ini` (the MLE, by default, may not always be a good starting point). That said, if setting the intercept to 0 helped in your case, I may suspect some linear dependence among your covariates. I can take a closer look at your data and diagnose where the algorithm crashes if you send them to me.
